test_that("`utils_time_keywords_translate()` works", {
  expect_equal(utils_time_keywords_translate(keyword = "1000 years"), )
  expect_equal(utils_time_keywords_translate(keyword = "1000 y"), )
  expect_equal(utils_time_keywords_translate(keyword = "thousands"), )
  expect_equal(utils_time_keywords_translate(keyword = "year"), )
  expect_equal(utils_time_keywords_translate(keyword = "y"), )
  expect_equal(utils_time_keywords_translate(keyword = "d"), )
  expect_equal(utils_time_keywords_translate(keyword = "day"), )
  expect_equal(utils_time_keywords_translate(keyword = "s"), )
  expect_equal(utils_time_keywords_translate(keyword = "sec"), )
})
