// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// auto_distance_cpp
double auto_distance_cpp(NumericMatrix m, Function f);
RcppExport SEXP _distantia_auto_distance_cpp(SEXP mSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(auto_distance_cpp(m, f));
    return rcpp_result_gen;
END_RCPP
}
// subset_matrix_by_rows_cpp
NumericMatrix subset_matrix_by_rows_cpp(NumericMatrix m, NumericVector rows);
RcppExport SEXP _distantia_subset_matrix_by_rows_cpp(SEXP mSEXP, SEXP rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rows(rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(subset_matrix_by_rows_cpp(m, rows));
    return rcpp_result_gen;
END_RCPP
}
// auto_sum_cpp
double auto_sum_cpp(NumericMatrix a, NumericMatrix b, DataFrame path, Function f);
RcppExport SEXP _distantia_auto_sum_cpp(SEXP aSEXP, SEXP bSEXP, SEXP pathSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type path(pathSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(auto_sum_cpp(a, b, path, f));
    return rcpp_result_gen;
END_RCPP
}
// cost_matrix_diag_cpp
NumericMatrix cost_matrix_diag_cpp(NumericMatrix dist_matrix);
RcppExport SEXP _distantia_cost_matrix_diag_cpp(SEXP dist_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_matrix(dist_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_matrix_diag_cpp(dist_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cost_matrix_weighted_diag_cpp
NumericMatrix cost_matrix_weighted_diag_cpp(NumericMatrix dist_matrix);
RcppExport SEXP _distantia_cost_matrix_weighted_diag_cpp(SEXP dist_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_matrix(dist_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_matrix_weighted_diag_cpp(dist_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cost_matrix_cpp
NumericMatrix cost_matrix_cpp(NumericMatrix dist_matrix);
RcppExport SEXP _distantia_cost_matrix_cpp(SEXP dist_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_matrix(dist_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_matrix_cpp(dist_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cost_path_cpp
DataFrame cost_path_cpp(NumericMatrix dist_matrix, NumericMatrix cost_matrix);
RcppExport SEXP _distantia_cost_path_cpp(SEXP dist_matrixSEXP, SEXP cost_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_matrix(dist_matrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cost_matrix(cost_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_path_cpp(dist_matrix, cost_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cost_path_diag_cpp
DataFrame cost_path_diag_cpp(NumericMatrix dist_matrix, NumericMatrix cost_matrix);
RcppExport SEXP _distantia_cost_path_diag_cpp(SEXP dist_matrixSEXP, SEXP cost_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dist_matrix(dist_matrixSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cost_matrix(cost_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_path_diag_cpp(dist_matrix, cost_matrix));
    return rcpp_result_gen;
END_RCPP
}
// cost_path_trim_cpp
DataFrame cost_path_trim_cpp(DataFrame path);
RcppExport SEXP _distantia_cost_path_trim_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_path_trim_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// cost_path_sum_cpp
double cost_path_sum_cpp(DataFrame path);
RcppExport SEXP _distantia_cost_path_sum_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cost_path_sum_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// distance_matrix_cpp
NumericMatrix distance_matrix_cpp(NumericMatrix a, NumericMatrix b, Function f);
RcppExport SEXP _distantia_distance_matrix_cpp(SEXP aSEXP, SEXP bSEXP, SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    rcpp_result_gen = Rcpp::wrap(distance_matrix_cpp(a, b, f));
    return rcpp_result_gen;
END_RCPP
}
// distance_manhattan_cpp
double distance_manhattan_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _distantia_distance_manhattan_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distance_manhattan_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distance_euclidean_cpp
double distance_euclidean_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _distantia_distance_euclidean_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distance_euclidean_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distance_hellinger_cpp
double distance_hellinger_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _distantia_distance_hellinger_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distance_hellinger_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// distance_chi_cpp
double distance_chi_cpp(NumericVector x, NumericVector y);
RcppExport SEXP _distantia_distance_chi_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(distance_chi_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distantia_auto_distance_cpp", (DL_FUNC) &_distantia_auto_distance_cpp, 2},
    {"_distantia_subset_matrix_by_rows_cpp", (DL_FUNC) &_distantia_subset_matrix_by_rows_cpp, 2},
    {"_distantia_auto_sum_cpp", (DL_FUNC) &_distantia_auto_sum_cpp, 4},
    {"_distantia_cost_matrix_diag_cpp", (DL_FUNC) &_distantia_cost_matrix_diag_cpp, 1},
    {"_distantia_cost_matrix_weighted_diag_cpp", (DL_FUNC) &_distantia_cost_matrix_weighted_diag_cpp, 1},
    {"_distantia_cost_matrix_cpp", (DL_FUNC) &_distantia_cost_matrix_cpp, 1},
    {"_distantia_cost_path_cpp", (DL_FUNC) &_distantia_cost_path_cpp, 2},
    {"_distantia_cost_path_diag_cpp", (DL_FUNC) &_distantia_cost_path_diag_cpp, 2},
    {"_distantia_cost_path_trim_cpp", (DL_FUNC) &_distantia_cost_path_trim_cpp, 1},
    {"_distantia_cost_path_sum_cpp", (DL_FUNC) &_distantia_cost_path_sum_cpp, 1},
    {"_distantia_distance_matrix_cpp", (DL_FUNC) &_distantia_distance_matrix_cpp, 3},
    {"_distantia_distance_manhattan_cpp", (DL_FUNC) &_distantia_distance_manhattan_cpp, 2},
    {"_distantia_distance_euclidean_cpp", (DL_FUNC) &_distantia_distance_euclidean_cpp, 2},
    {"_distantia_distance_hellinger_cpp", (DL_FUNC) &_distantia_distance_hellinger_cpp, 2},
    {"_distantia_distance_chi_cpp", (DL_FUNC) &_distantia_distance_chi_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_distantia(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
