#' Auto Breaks for Matrix Plotting Functions
#'
#' @param m (required, numeric matrix) distance or cost matrix generated by [distance_matrix()] or [cost_matrix()], but any numeric matrix will work. Default: NULL
#' @param n (required, integer) number of colors to compute the breaks for. Default: 100
#'
#' @return Numeric vector
#' @autoglobal
#' @export
auto_breaks <- function(
    m = NULL,
    n = 100
    ){

  #check m
  m <- check_args_matrix(m = m)

  if(inherits(x = m, what = "matrix") == FALSE){
    stop("Argument 'm' must be a distance or cost matrix resulting from distantia::distance_matrix() or distantia::cost_matrix().")
  }

  m.range <- range(m, na.rm = TRUE)

  a <- seq(
    from = m.range[1],
    to = m.range[2],
    length.out = n
  )

  b <- (a[2]- a[1])/2

  breaks <- c(a[1] - b, a + b)

  breaks

}
