#' Dissimilarity Model Frame
#'
#' @description
#' Generates a model frame from a dissimilarity data frame generated by [distantia()] and a data frame static descriptors of the time series.
#'
#'
#' @inheritParams distantia_matrix
#' @param predictors_df (required, data frame) data frame with numeric predictors to be added to the model frame. Must have a column with the names in `df$x` and `df$y`. If `sf` data frame, the predictor "distance" is added to the model frame. Default: NULL
#' @param predictors_list (optional, list) list defining predictors as combinations fo columns in `predictors_df`. For example, `predictors_list = list(distance = c("x", "y"))` uses the columns `"x"` and `"y"` from `predictors_df` to generate the predictor `distance` in the model frame. Can be used to combine groups of predictors with common themes. Any column from `predictors_df` not in this list is returned as an individual predictor in the model frame. Default: NULL
#' @inheritParams distantia
#'
#' @return data frame
#' @export
#' @autoglobal
#' @examples
#' #covid prevalence in California counties
#' tsl <- tsl_initialize(
#'   x = covid_prevalence,
#'   name_column = "name",
#'   time_column = "time"
#' )
#'
#' #dissimilarity analysis
#' df <- distantia(
#'   tsl = tsl,
#'   lock_step = TRUE
#' )
#'
#' #combine predictors together
#' predictors_list <- list(
#'   economy = c(
#'     "poverty_percentage",
#'     "median_income",
#'     "domestic_product"
#'     )
#' )
#'
#' #generate model frame
#' model_frame <- distantia_model_frame(
#'   df = df,
#'   predictors_df = covid_counties,
#'   predictors_list = predictors_list
#' )
#'
#' head(model_frame)
#' @family dissimilarity_analysis_main
distantia_model_frame <- function(
    df = NULL,
    predictors_df = NULL,
    predictors_list = NULL,
    distance = "euclidean"
){

  #df ----
  if(is.null(df)){

    stop(
      "distantia::distantia_model_frame(): argument `df' must not be NULL.",
      call. = FALSE
    )

  }

  if(attributes(df)$type != "distantia_df"){

    stop(
      "distantia::distantia_model_frame(): argument 'df' must be the output of distantia::distantia().",
      call. = FALSE
    )

  }

  #simplify distantia data frame
  df <- distantia_aggregate(
    df = df,
    f = mean
  )

  #add ID
  df$id <- seq_len(nrow(df))

  #predictors_df ----
  if(is.null(predictors_df)){

    stop(
      "distantia::distantia_model_frame(): argument `predictors_df' must not be NULL.",
      call. = FALSE
    )

  }

  if(!inherits(x = predictors_df, what = "data.frame")){

    stop(
      "distantia::distantia_model_frame(): argument `predictors_df' must be a data frame.",
      call. = FALSE
    )

  }

  #identify names column in predictors df
  df_names <- unique(
    c(df$x, df$y)
  )

  predictors_name_column <- sapply(
    X = predictors_df,
    FUN = function(x){
      sum(df_names %in% x) == length(df_names)
    }
  )

  predictors_name_column <- names(predictors_name_column[which(predictors_name_column)])

  if(length(predictors_name_column) == 0){
    stop(
      "distantia::distantia_model_frame(): argument 'predictors_df' must have a column with the names in 'df$x' and 'df$y'.",
      call. = FALSE
    )
  }

  #numeric columns
  predictors_numeric_columns <- sapply(
    X = predictors_df,
    FUN = is.numeric
  )

  predictors_numeric_columns <- names(predictors_numeric_columns[which(predictors_numeric_columns)])

  if(length(predictors_numeric_columns) == 0){
    stop(
      "distantia::distantia_model_frame(): argument 'predictors_df' must have at least one numeric column, but it has none.",
      call. = FALSE
    )
  }

  #predictors list ----

  #default predictors list
  predictors_list_default <- as.list(
    predictors_numeric_columns
  )

  names(predictors_list_default) <- predictors_numeric_columns

  #predictors list
  if(is.null(predictors_list)){

    predictors_list <- predictors_list_default

  } else {

    #add names if not named
    if(is.null(names(predictors_list))){
      names(predictors_list) <- sapply(
        X = predictors_list,
        FUN = function(x){
          paste(x, collapse = "_")
        }
      )
    }

    predictors_list_default <- predictors_list_default[!(names(predictors_list_default) %in% names(predictors_list))]

    predictors_list <- c(
      predictors_list,
      predictors_list_default
    )

  }

  #remove geometry
  predictors_df_no_geom <- utils_drop_geometry(
    df = predictors_df
    )

  #id df
  df.id <- df[, "id", drop = FALSE]

  #progress bar
  p <- progressr::progressor(along = predictors_list)

  #compute distance matrices
  model_frame_list <- future.apply::future_lapply(
    X = seq_len(length(predictors_list)),
    FUN = function(x){

      # p()

      #extract predictors columns
      df.i <- predictors_df_no_geom[
        ,
        unlist(predictors_list[[x]]),
        drop = FALSE
        ]

      #decide if scaling is needed
      sd_ratios <- max(sapply(X = df.i, FUN = sd)) /
        min(sapply(X = df.i, FUN = sd))

      if(sd_ratios > 10){

        df.i <- df.i |>
          scale() |>
          as.data.frame()

      }

      #add name column
      df.i[[predictors_name_column]] <- predictors_df[[predictors_name_column]]

      #compute distance matrix
      m.i <- distantia::distance_matrix(
        df = df.i,
        name_column = predictors_name_column,
        distance = distance
      )

      #prepare df
      out.df.i <- df.id

      #extract matrix as vector
      variable.i <- mapply(
        FUN = function(a, b) m.i[a, b],
        df$x,
        df$y
      )

      names(variable.i) <- NULL

      out.df.i[[names(predictors_list)[x]]] <- variable.i

      out.df.i

    }
  )

  names(model_frame_list) <- names(predictors_list)

  #add geographic distance if predictors_df is an sf data frame
  if(
    !is.null(attributes(predictors_df)$sf_column) &&
    requireNamespace("sf", quietly = TRUE) &&
    requireNamespace("lwgeom", quietly = TRUE)
  ){

    m.i <- sf::st_distance(
      x = predictors_df
    )

    dimnames(m.i) <- list(
      as.character(predictors_df[[predictors_name_column]]),
      as.character(predictors_df[[predictors_name_column]])
    )

    variable.i <- mapply(
      FUN = function(a, b) m.i[a, b],
      df$x,
      df$y
    )

    names(variable.i) <- NULL

    new_distance_column <- "distance"
    if(new_distance_column %in% names(model_frame_list)){
      new_distance_column <- "geometry_distance"
    }

    df.id[[new_distance_column]] <- variable.i

    #add to model frame list
    model_frame_list <- c(
      list(distance = df.id),
      model_frame_list
    )


  }


  #add distantia df
  model_frame_list <- c(
    list(response = df),
    model_frame_list
  )

  #join all data frames
  model_frame <- Reduce(
    f = function(x, y){
      merge(x, y, by = "id")
    },
    x = model_frame_list
  )

  model_frame$id <- NULL

  model_frame


}
