# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "distances", # <auto_sum>
  "distances", # <argument_distance>
  "group_size_a", # <cost_path_trim>
  "cost", # <cost_path_trim>
  "group_size_b", # <cost_path_trim>
  "distances", # <distance_matrix>
  "i", # <distantia_parallel>
  "distances", # <importance>
  NULL
))
