# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "distances", # <distance>
  "i", # <distantia>
  "i", # <distantia_importance>
  "group_size_y", # <psi_cost_path_trim_blocks>
  "cost", # <psi_cost_path_trim_blocks>
  "group_size_x", # <psi_cost_path_trim_blocks>
  "na.omit", # <f_detrend_gam>
  "sd", # <scaling_parameters>
  "distances", # <utils_check_distance_args>
  "median", # <zoo_aggregate>
  "i", # <zoo_permute>
  NULL
))
