# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "distances", # <check_args_distance>
  "group_size_a", # <cost_path_trim>
  "cost", # <cost_path_trim>
  "group_size_b", # <cost_path_trim>
  "a.names", # <distance_matrix>
  "b.names", # <distance_matrix>
  "i", # <distantia>
  "i", # <importance>
  "b", # <slotting>
  "a_", # <slotting>
  "b_", # <slotting>
  "b", # <slotting>
  "a_", # <slotting>
  "b_", # <slotting>
  NULL
))
