#' Plots Multivariate Sequences
#'
#' @param x (required, matrix) One element of a list generated by [prepare_sequences()]. Default: NULL
#' @param center (optional, logical) If TRUE, the columns of `x` are centered via [scale()]. Default: FALSE
#' @param scale (optional, logical) If TRUE, the columns of `x` are scaled via [scale()]. Default: FALSE
#' @param color (optional, character vector) vector of colors for the distance or cost matrix. If NULL, uses the palette "Zissou 1" provided by the function [grDevices::hcl.colors()]. Default: NULL
#' @param width (optional, numeric vector) Widths of the sequence curves. Default: 1
#' @param title (optional, character string) Main title of the plot. If NULL, it's set to the name of the sequence. Default: NULL
#' @param xlab (optional, character string) Title of the x axis. Disabled if `subpanel` or `vertical` are TRUE. If NULL, the word "Time" is used. Default: NULL
#' @param ylab (optional, character string) Title of the x axis. Disabled if `subpanel` or `vertical` are TRUE. If NULL, it is left empty. Default: NULL
#' @param text_cex (optional, numeric) Multiplicator of the text size. Default: 1
#' @param guide (optional, logical) If TRUE, plots a legend. Default: TRUE
#' @param guide_position (optional, character string) Position of the guide. Accepted values are: "bottomright", "bottom", "bottomleft", "left", "topleft", "top", "topright", "right" and "center". Default: "topright"
#' @param guide_cex (optional, numeric) Size of the guide's text and separation between the guide's rows. Default: 0.7.
#' @param vertical (optional, logical) For internal use within the package in multipanel plots. Switches the plot axes. Disabled if `subpanel = FALSE`. Default: FALSE
#' @param subpanel (optional, logical) For internal use within the package in multipanel plots. Strips down the plot for a sub-panel. Default: FALSE
#'
#' @return A plot.
#' @export
#'
#' @examples
plot_sequence <- function(
    x = NULL,
    center = FALSE,
    scale = FALSE,
    color = NULL,
    width = 1,
    title = NULL,
    xlab = NULL,
    ylab = NULL,
    text_cex = 1,
    box = FALSE,
    guide = TRUE,
    guide_position = "topright",
    guide_cex = 0.8,
    vertical = FALSE,
    subpanel = FALSE
){

  # Preserve user's config
  if(subpanel == FALSE){
    old.par <- par(no.readonly = TRUE)
    on.exit(par(old.par))
  }

  #check x
  x <- check_args_x(x = x)

  #axis title
  axis_title_distance <- 1.4
  axis_title_cex <- 0.9 * text_cex

  #axis labels
  axis_labels_cex <- 0.7 * text_cex

  #title
  main_title_distance <- 1.2
  main_title_cex <- 1.2 * text_cex

  if(subpanel == FALSE){

    axis_title_distance <- 2.2
    axis_labels_cex <- 0.8 * text_cex
    vertical <- FALSE

  }

  #x to data frame
  if(any(c(center, scale))){

    df <- scale(
      x = x,
      scale = scale,
      center = center,
    ) |>
      as.data.frame()

  } else {
    #to data frame
    df <- as.data.frame(x)
  }

  #time column
  df.time <- as.numeric(attributes(x)$time)

  #name
  df.name <- attributes(x)$sequence_name

  #names of columns to plot
  df.columns <- colnames(df)

  #default palette
  if(is.null(color)){
    color <- grDevices::hcl.colors(
      n = length(df.columns),
      palette = "Zissou 1"
    )
  } else {
    #subset input palette
    if(length(color) > (length(df.columns) * 2)){
      color <- color[
        seq(
          from = 1,
          to = length(color),
          length.out = length(df.columns))
      ]
    }
  }

  #width
  if(length(width) == 1){
    width <- rep(
      x = width,
      times = length(df.columns)
    )
  }

  if(length(width) != length(df.columns)){
    if(width[1] < width[length(width)]){
      width <- seq(
        from = min(width),
        to = max(width),
        length.out = length(df.columns)
      )
    } else {
      width <- seq(
        from = max(width),
        to = min(width),
        length.out = length(df.columns)
      )
    }
  }

  #data limits
  df.min <- min(df, na.rm = TRUE)
  df.max <- max(df, na.rm = TRUE)
  df.range <- df.max - df.min

  if(subpanel == TRUE){
    df.lim <- c(
      df.min,
      df.max + (df.range / 5)
    )
  } else {
    df.lim <- df.range
  }


  #first plot
  if(vertical == FALSE){

    plot.x <- df.time
    plot.y <- df[, df.columns[1]]
    x.axis.side <- 1
    y.axis.side <- 2
    y.lim <- df.lim
    x.lim <- NULL
    df.name.x <- df.name
    df.name.y <- NULL

  } else {

    plot.x <- df[, df.columns[1]]
    plot.y <- df.time
    x.axis.side <- 2
    y.axis.side <- 3
    y.lim <- NULL
    x.lim <- rev(df.lim)
    df.name.x <- NULL
    df.name.y <- df.name

  }

  if(box == FALSE){
    par(bty = "n")
  }

  #first plot
  graphics::plot(
    x = plot.x,
    y = plot.y,
    xlab = "",
    type = "l",
    ylab = "",
    xaxt = "n",
    yaxt = "n",
    ylim = y.lim,
    xlim = x.lim,
    lwd = width[1],
    col = color[1]
  )

  graphics::axis(
    side = x.axis.side,
    las = 1,
    cex.axis = axis_labels_cex
  )

  graphics::axis(
    side = y.axis.side,
    las = 1,
    cex.axis = axis_labels_cex
  )

  #add all the other lines
  for(i in seq(2, length(df.columns))){

    if(vertical == FALSE){
      line.x <- df.time
      line.y <- df[, df.columns[i]]
    } else {
      line.x <- df[, df.columns[i]]
      line.y <- df.time
    }

    graphics::lines(
      x = line.x,
      y = line.y,
      lwd = width[i],
      col = color[i]
    )

  }

  #decoration
  if(subpanel == FALSE){

    graphics::title(
      main = ifelse(
        test = is.null(title),
        yes = df.name,
        no = title
      ),
      cex.main = main_title_cex,
      line = main_title_distance
    )

    graphics::title(
      xlab = ifelse(
        test = is.null(xlab),
        yes = "",
        no = xlab
      ),
      line = axis_title_distance,
      cex.lab = axis_title_cex
    )

    graphics::title(
      ylab = ifelse(
        test = is.null(ylab),
        yes = "",
        no = ylab
      ),
      line = axis_title_distance,
      cex.lab = axis_title_cex
    )

  } else {

    graphics::title(
      xlab = df.name.x,
      ylab = df.name.y,
      cex.lab = axis_title_cex,
      line = axis_title_distance
    )


  }

  if(guide == TRUE){

    plot_line_guide(
      x = x,
      position = guide_position,
      color = color,
      width = width,
      text_cex = guide_cex,
      box = box,
      subpanel = FALSE
    )

  }



}


