#' Plot Distance or Cost Matrix
#'
#' @description
#' This function is a simplified version of [fields::imagePlot()], by [Douglas Nychka](https://dnychka.github.io/). The original version is recommended in case more customization than the provided here is needed.
#'
#'
#' @param m (required, numeric matrix) distance or cost matrix generated by [distance_matrix()] or [cost_matrix()], but any numeric matrix will work. Default: NULL
#' @param matrix_color (optional, character vector) vector of colors. Default: NULL
#' @param main_title (optional, character string) plot title. Default: NULL
#' @param xlab (optional, character string) title of the x axis (matrix columns). Default: NULL
#' @param ylab (optional, character string) title of the y axis (matrix rows). Default: NULL
#' @param guide_title (optional, character string) title of the color guide. Default: NULL
#' @param path (optional, data frame) least cost path generated with [cost_path()]. This data frame must have the attribute `type == "cost_path`, or otherwise it will be ignored. Default: NULL.
#' @param path_width (optional, numeric) width of the least-cost path. Default: 1
#' @param path_color (optional, character string) color of the least-cost path. Default: "black"
#' @param cex (optional, numeric) multiplicator for the text size. Default: 1
#'
#' @return A plot
#' @examples
#'
#' #' library(distantia)
#'
#' load("~/Dropbox/GITHUB/R_packages/distantia/data/sequencesMIS.RData")
#'
#' #data frame with grouping column
#' ###################################
#' data(sequencesMIS)
#'
#' #prepare list of sequences
#' x <- prepare_sequences(
#'   x = sequencesMIS,
#'   id_column = "MIS",
#'   time_column = NULL,
#'   paired_samples = FALSE,
#'   pseudo_zero =  0.001,
#'   na_action = "to_zero"
#' )
#'
#' #distance matrix of the first two sequences
#' dist_matrix <- distance_matrix(
#'   a = x[[1]],
#'   b = x[[2]],
#'   distance = "euclidean"
#' )
#'
#' #cost matrix
#' cost_matrix <- cost_matrix(
#'   dist_matrix = dist_matrix
#'   )
#'
#' #least cost path
#' path <- cost_path(
#'   dist_matrix = dist_matrix,
#'   cost_matrix = cost_matrix
#' )
#'
#' #plot cost matrix and least cost path
#' plot_matrix(
#'   m = cost_matrix,
#'   path = path
#'   )
#'
#' @export
#' @autoglobal
plot_panel <- function(
    m = NULL,
    matrix_color = NULL,
    main_title = NULL,
    xlab = NULL,
    ylab = NULL,
    guide_title = NULL,
    path = NULL,
    path_width = 1,
    path_color = "black",
    cex = 1
){

  if(is.null(matrix_color)){
    matrix_color = grDevices::hcl.colors(
      n = 100,
      palette = "Zissou 1"
    )
  }

  #a few hardcoded guide parameters
  guide_area_factor <- 0.1
  guide_width = 1.2
  guide_margin <- 5.1

  #save and reset the user's graphical parameters
  old.par <- par(no.readonly = TRUE)
  on.exit(par(old.par))

  #handling main and guide area
  old.par <- par(no.readonly = TRUE)
  text_size <- par()$cin[1]/par()$din[1]
  offset <- text_size * par()$mar[4]
  guide_width <- text_size * guide_width
  guide_margin <- guide_margin * text_size
  guide_area <- old.par$plt
  guide_area[2] <- 1 - guide_margin
  guide_area[1] <- guide_area[2] - guide_width
  pr <- (guide_area[4] - guide_area[3]) * ((guide_area_factor)/2)
  guide_area[4] <- guide_area[4] - pr
  guide_area[3] <- guide_area[3] + pr

  #handling main area
  main_area <- old.par$plt
  main_area[2] <- min(main_area[2], guide_area[1] - offset)
  guide_area[1] <- min(main_area[2] + offset, guide_area[1])
  guide_area[2] <- guide_area[1] + (guide_area[2] - guide_area[1])

  #main plot
  par(plt = main_area)

  #matrix and path plot
  plot_matrix(
    m = m,
    matrix_color = matrix_color,
    title = main_title,
    xlab = xlab,
    ylab = ylab,
    path = path,
    path_width = path_width,
    path_color = path_color,
    cex = cex
  )

  big.par <- par(no.readonly = TRUE)

  #PLOT LEGEND
  if(
    (guide_area[2] > guide_area[1]) &&
    (guide_area[4] > guide_area[3])
  ){

    #guide plot
    par(
      new = TRUE,
      pty = "m",
      plt = guide_area,
      err = -1
    )

    plot_guide(
      m = m,
      color = matrix_color,
      breaks = breaks,
      title = guide_title
    )

  } else {

    warning("Plotting area is too small to add a color guide.")

  }

  invisible()

}

