#' Plot Multivariate Sequences
#'
#' @description
#' Designed to help quickly explore a set of sequences.
#'
#'
#' @param x (required, matrix) List of sequences generated by [prepare_sequences()]. Default: NULL
#' @param center (optional, logical) If TRUE, the columns of `x` are centered via [scale()]. Default: FALSE
#' @param scale (optional, logical) If TRUE, the columns of `x` are scaled via [scale()]. Default: FALSE
#' @param columns (optional, integer) Number of columns to organize the sequence plots into. Default: 1
#' @param xlim (optional, numeric vector) Numeric vector with the limits of the x axis. Applies to all sequences. Default: NULL
#' @param ylim (optional, numeric vector) Numeric vector with the limits of the x axis. Applies to all sequences. Default: NULL
#' @param color (optional, character vector) vector of colors for the distance or cost matrix. If NULL, uses an appropriate palette generated with [grDevices::palette.colors()]. Default: NULL
#' @param width (optional, numeric vector) Widths of the sequence curves. Default: 1
#' @param text_cex (optional, numeric) Multiplicator of the text size. Default: 1
#' @param guide (optional, logical) If TRUE, plots a legend. Default: TRUE
#' @param guide_columns (optional, integer) Columns of the line guide. Default: 1.
#' @param guide_cex (optional, numeric) Size of the guide's text and separation between the guide's rows. Default: 0.7.
#'
#' @return A plot.
#' @export
#'
#' @examples
plot_sequences <- function(
    x = NULL,
    center = FALSE,
    scale = FALSE,
    columns = 1,
    xlim = NULL,
    ylim = NULL,
    color = NULL,
    width = 1,
    text_cex = 1,
    guide = TRUE,
    guide_columns = 1,
    guide_cex = 0.8
){

  axis_title_distance <- 2.2

  # Preserve user's config
  old.par <- par(no.readonly = TRUE)
  on.exit(par(old.par))

  #check x
  x <- check_args_x(x = x)

  #get column names
  x_colnames <- lapply(
    X = x,
    FUN = function(z){
      attributes(z)$dimnames[[2]]
    }
  ) |>
    unlist() |>
    unique()

  #generate colors
  color <- plot_utils_line_color(
    x = x,
    color = color
  )

  #define new par
  if(guide == TRUE){
    n_panels <- length(x) + 1
  } else {
    n_panels <- length(x)
  }

  rows <- ceiling(n_panels/columns)

  par(
    mfrow = c(rows, columns),
    oma = c(1.2, 0, 0, 1),
    mar = c(1, 3.5, 1, 0.5)
  )

  #plot panels
  for(i in seq_len(n_panels)){

    if(i <= length(x)){

      plot_sequence(
        x = x[[i]],
        center = center,
        scale = scale,
        color = color,
        xlim = xlim,
        ylim = ylim,
        width = width,
        title = "",
        xlab = NULL,
        ylab = "",
        text_cex = text_cex,
        box = FALSE,
        guide = FALSE,
        guide_position = "right",
        guide_cex = guide_cex,
        subpanel = TRUE
      )

      graphics::title(
        ylab = attributes(x[[i]])$sequence_name,
        line = axis_title_distance,
        cex.lab = text_cex
      )

    } else {

      if(guide == TRUE){
        plot_utils_line_guide(
          x = x,
          position = "center",
          color = color,
          width = width,
          text_cex = guide_cex,
          ncol = guide_columns,
          subpanel = TRUE
        )
      }

    }

  }

  invisible()

}
