# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Auto Distance
#' @description Computes the distance matrix between the rows of two matrices
#' \code{a} and \code{b} with the same number of columns and arbitrary numbers of rows.
#' NA values should be removed before using this function.
#' If the selected distance function is [distance_chi_cpp], pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#'  of the dataset `methods`. Default: "euclidean".
#' @return Matrix of distances between 'a' (rows) and 'b' (columns).
#' @export
auto_distance_cpp <- function(m, method) {
    .Call(`_distantia_auto_distance_cpp`, m, method)
}

#' Subset Matrix by Rows
#' @description Subsets the matrix \code{m} to the indices given in the vector \code{rows}.
#' Used to subset a sequence to the coordinates of a trimmed least-cost path.
#' @param m (required, numeric matrix) a sequence.
#' @param rows (required, integer vector) vector of rows to subset.
#' @return Numeric matrix of length rows.
#' @export
subset_matrix_by_rows_cpp <- function(m, rows) {
    .Call(`_distantia_subset_matrix_by_rows_cpp`, m, rows)
}

#'Auto-sum of Two Paired Sequences
#' @description Sum of the the cumulative auto-sum of two sequences with paired samples. This is
#' a key component of the psi computation.
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @return Numeric.
#' @export
auto_sum_no_path_cpp <- function(a, b, method) {
    .Call(`_distantia_auto_sum_no_path_cpp`, a, b, method)
}

#'Auto-sum of Two Sequences
#' @description Sum of the the cumulative auto-sum of two sequences. This is
#' a key component of the psi computation.
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param path (required, data frame) dataframe produced by [cost_path()].
#' Default: NULL
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @return Numeric.
#' @export
auto_sum_path_cpp <- function(a, b, path, method) {
    .Call(`_distantia_auto_sum_path_cpp`, a, b, path, method)
}

#' Least Cost Matrix Considering Diagonals
#' @description Computes the least cost matrix from a distance matrix.
#' Considers diagonals during computation of least-costs.
#' @param d (required, distance matrix). Distance matrix.
#' @return Least cost matrix.
#' @export
cost_matrix_diag_cpp <- function(dist_matrix) {
    .Call(`_distantia_cost_matrix_diag_cpp`, dist_matrix)
}

#' Least Cost Matrix with Weighted Diagonals
#' @description Computes the least cost matrix from a distance matrix.
#' Weights diagonals by a factor of 1.414214 with respect to orthogonal paths.
#' @param dist_matrix (required, distance matrix). Distance matrix.
#' @return Least cost matrix.
#' @export
cost_matrix_weighted_diag_cpp <- function(dist_matrix) {
    .Call(`_distantia_cost_matrix_weighted_diag_cpp`, dist_matrix)
}

#' Least Cost Matrix
#' @description Computes the least cost matrix from a distance matrix.
#' @param dist_matrix (required, distance matrix). Output of [distance_matrix_cpp()].
#' @return Least cost matrix.
#' @export
cost_matrix_cpp <- function(dist_matrix) {
    .Call(`_distantia_cost_matrix_cpp`, dist_matrix)
}

#' Least Cost Path
#' @description Computes the least cost matrix from a distance matrix.
#' Considers diagonals during computation of least-costs.
#' @param dist_matrix (required, distance matrix). Distance matrix.
#' @param cost_matrix (required, numeric matrix) Cost matrix generated from the distance matrix.
#' @return A data frame with least-cost path coordiantes.
#' @export
cost_path_cpp <- function(dist_matrix, cost_matrix) {
    .Call(`_distantia_cost_path_cpp`, dist_matrix, cost_matrix)
}

#' Least Cost Path Considering Diagonals
#' @description Computes the least cost matrix from a distance matrix.
#' Considers diagonals during computation of least-costs.
#' @param dist_matrix (required, distance matrix). Distance matrix.
#' @param cost_matrix (required, numeric matrix) Cost matrix generated from the distance matrix.
#' @return A data frame with least-cost path coordiantes.
#' @export
cost_path_diag_cpp <- function(dist_matrix, cost_matrix) {
    .Call(`_distantia_cost_path_diag_cpp`, dist_matrix, cost_matrix)
}

#' Trims Blocks from Least Cost Path
#' @param path (required, data frame) dataframe produced by [cost_path()]. Default: NULL
#' @return A data frame with least-cost path coordinates.
#' @export
cost_path_trim_cpp <- function(path) {
    .Call(`_distantia_cost_path_trim_cpp`, path)
}

#' Sum of Least Cost Distance
#' @param path (required, data frame) dataframe produced by [cost_path()]. Default: NULL
#' @return Sum of distances
#' @export
cost_path_sum_cpp <- function(path) {
    .Call(`_distantia_cost_path_sum_cpp`, path)
}

#' Distance Matrix
#' @description Computes the distance matrix between the rows of two matrices
#' \code{a} and \code{b} with the same number of columns and arbitrary numbers
#' of rows.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @return Matrix of distances between 'a' (rows) and 'b' (columns).
#' @export
#' @name distance_matrix_cpp
distance_matrix_cpp <- function(a, b, method) {
    .Call(`_distantia_distance_matrix_cpp`, a, b, method)
}

#' Distance Matrix
#' @description Computes the vector of distances between paired rows in two
#' sequences of the same length.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns and rows as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @return Vector of distances between 'a' (rows) and 'b' (columns).
#' @export
distance_pairwise_cpp <- function(a, b, method) {
    .Call(`_distantia_distance_pairwise_cpp`, a, b, method)
}

#' Chebyshev Distance Between Two Vectors
#' @description Computed as: \code{max(abs(x - y))}. Cannot handle NA values.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Chebyshev distance between x and y.
#' @examples distance_chebyshev_cpp(x = runif(100), y = runif(100))
#' @export
distance_chebyshev_cpp <- function(x, y) {
    .Call(`_distantia_distance_chebyshev_cpp`, x, y)
}

#' Jaccard Distance Between Two Binary Vectors
#' @description Computes the Jaccard distance between two binary vectors.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Jaccard distance between x and y.
#' @examples distance_jaccard_cpp(c(0, 1, 0, 1), c(1, 1, 0, 0))
#' @export
distance_jaccard_cpp <- function(x, y) {
    .Call(`_distantia_distance_jaccard_cpp`, x, y)
}

#' Manhattan Distance Between Two Vectors
#' @description Computed as: \code{sum(abs(x - y))}. Cannot handle NA values.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Manhattan distance between x and y.
#' @examples distance_manhattan_cpp(x = runif(100), y = runif(100))
#' @export
distance_manhattan_cpp <- function(x, y) {
    .Call(`_distantia_distance_manhattan_cpp`, x, y)
}

#' Euclidean Distance Between Two Vectors
#' @description Computed as: \code{sqrt(sum((x - y)^2)}. Cannot handle NA values.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Euclidean distance between x and y.
#' @examples distance_euclidean_cpp(x = runif(100), y = runif(100))
#' @export
distance_euclidean_cpp <- function(x, y) {
    .Call(`_distantia_distance_euclidean_cpp`, x, y)
}

#' Hellinger Distance Between Two Vectors
#' @description Computed as: \code{sqrt(1/2 * sum((sqrt(x) - sqrt(y))^2))}.
#' Cannot handle NA values.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Hellinger distance between x and y.
#' @examples distance_hellinger_cpp(x = runif(100), y = runif(100))
#' @export
distance_hellinger_cpp <- function(x, y) {
    .Call(`_distantia_distance_hellinger_cpp`, x, y)
}

#' Normalized Chi Distance Between Two Vectors
#' @description Computed as:
#' \code{xy <- x + y}
#' \code{y. <- y / sum(y)}
#' \code{x. <- x / sum(x)}
#' \code{sqrt(sum(((x. - y.)^2) / (xy / sum(xy))))}.
#' Cannot handle NA values. When \code{x} and \code{y} have zeros in the same
#' position, \code{NaNs} are produced. Please replace these zeros with
#' pseudo-zeros (i.e. 0.0001) if you wish to use this distance metric.
#' @examples distance_chi_cpp(x = runif(100), y = runif(100))
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Chi distance between x and y.
#' @export
distance_chi_cpp <- function(x, y) {
    .Call(`_distantia_distance_chi_cpp`, x, y)
}

#' Canberra Distance Between Two Binary Vectors
#' @description Computes the Canberra distance between two binary vectors.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.//' @return Canberra distance between x and y.
#' @examples distance_canberra_cpp(c(0, 1, 0, 1), c(1, 1, 0, 0))
#' @export
distance_canberra_cpp <- function(x, y) {
    .Call(`_distantia_distance_canberra_cpp`, x, y)
}

#' Russell-Rao Distance Between Two Binary Vectors
#' @description Computes the Russell-Rao distance between two binary vectors.
#' @param x (required, numeric). Binary vector of 1s and 0s.
#' @param y (required, numeric) Binary vector of 1s and 0s of same length as `x`.
#' @return Russell-Rao distance between x and y.
#' @examples distance_russelrao_cpp(c(0, 1, 0, 1), c(1, 1, 0, 0))
#' @export
distance_russelrao_cpp <- function(x, y) {
    .Call(`_distantia_distance_russelrao_cpp`, x, y)
}

#' Cosine Dissimilarity Between Two Vectors
#' @description Computes the cosine dissimilarity between two numeric vectors.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Cosine dissimilarity between x and y.
#' @examples distance_cosine_cpp(c(0.2, 0.4, 0.5), c(0.1, 0.8, 0.2))
#' @export
distance_cosine_cpp <- function(x, y) {
    .Call(`_distantia_distance_cosine_cpp`, x, y)
}

#' Hamming Distance Between Two Binary Vectors
#' @description Computes the Hamming distance between two binary vectors.
#' @param x (required, numeric vector).
#' @param y (required, numeric vector) of same length as `x`.
#' @return Hamming distance between x and y.
#' @examples distance_hamming_cpp(c(0, 1, 0, 1), c(1, 1, 0, 0))
#' @export
distance_hamming_cpp <- function(x, y) {
    .Call(`_distantia_distance_hamming_cpp`, x, y)
}

#' Restricted permutation
#' @description Divides a sequence or time-series in blocks and permutes rows
#' within these blocks. Used to compute p-values for psi distances. Larger block
#' sizes disrupt the time-series structure in the data.
#' @param x (required, numeric matrix). Numeric matrix to permute.
#' @param block_size (optional, integer) block size in number of rows.
#' Minimum value is 2, and maximum value is nrow(x).
#' @param seed (optional, integer) random seed to use.
#' @return Numeric matrix, permuted version of x.
#' @export
permute <- function(x, block_size, seed = 1L) {
    .Call(`_distantia_permute`, x, block_size, seed)
}

#' Computes Psi Distance Between Two Time-Series With Paired Samples
#' @description Computes the distance psi between two matrices
#' \code{a} and \code{b} with the same number of columns and rows. Distances
#' between \code{a} and \code{b} are computed row wise rather than via distance
#' matrix and least-cost path computation.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @return Psi distance
#' @export
psi_paired_cpp <- function(a, b, method) {
    .Call(`_distantia_psi_paired_cpp`, a, b, method)
}

#' Computes Psi Distance Between Two Time-Series
#' @description Computes the distance psi between two matrices
#' \code{a} and \code{b} with the same number of columns and arbitrary numbers of rows.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @param diagonal (optional, logical). If TRUE, diagonals are included in the
#' computation of the cost matrix. Default: FALSE.
#' @param weighted (optional, logical). If TRUE, diagonal is set to TRUE, and
#' diagonal cost is weighted by a factor of 1.414214. Default: FALSE.
#' @param trim_blocks (optional, logical). If TRUE, blocks of consecutive path
#' coordinates are trimmed to avoid inflating the psi distance. Default: FALSE.
#' @return Psi distance
#' @export
psi_full_cpp <- function(a, b, method, diagonal = FALSE, weighted = FALSE, trim_blocks = FALSE) {
    .Call(`_distantia_psi_full_cpp`, a, b, method, diagonal, weighted, trim_blocks)
}

#' Computes Null Distribution of Psi Distances Between Two Time-Series With Paired Samples
#' @description Computes the distance psi between two matrices
#' \code{a} and \code{b} with the same number of columns and rows. Distances
#' between \code{a} and \code{b} are computed row wise rather than via distance
#' matrix and least-cost path computation.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @param block_size (optional, integer vector) vector with block sizes for the
#' restricted permutation. A block size of 3 indicates that a row can only be permuted
#' within a block of 3 adjacent rows. Default: c(2, 3, 4).
#' @param seed (optional, integer) initial random seed to use for replicability. Default: 1
#' @param repetitions (optional, integer) number of null psi values to generate. Default: 100
#' @return Psi distance
#' @export
null_psi_paired_cpp <- function(a, b, method, block_size = as.integer( c(2, 3, 4)), seed = 1L, repetitions = 100L) {
    .Call(`_distantia_null_psi_paired_cpp`, a, b, method, block_size, seed, repetitions)
}

#' Computes Psi Distance Between Two Time-Series
#' @description Computes the distance psi between two matrices
#' \code{a} and \code{b} with the same number of columns and arbitrary numbers of rows.
#' NA values should be removed before using this function.
#' If the selected distance function is "chi" or "cosine", pairs of zeros should
#' be either removed or replaced with pseudo-zeros (i.e. 0.00001).
#' @param a (required, numeric matrix).
#' @param b (required, numeric matrix) of same number of columns as 'a'.
#' @param method (optional, character string) name or abbreviation of the
#' distance method. Valid values are in the columns "names" and "abbreviation"
#' of the dataset `methods`. Default: "euclidean".
#' @param diagonal (optional, logical). If TRUE, diagonals are included in the
#' computation of the cost matrix. Default: FALSE.
#' @param weighted (optional, logical). If TRUE, diagonal is set to TRUE, and
#' diagonal cost is weighted by a factor of 1.414214. Default: FALSE.
#' @param trim_blocks (optional, logical). If TRUE, blocks of consecutive path
#' coordinates are trimmed to avoid inflating the psi distance. This argument
#' has nothing to do with block_size!. Default: FALSE.
#' @param block_size (optional, integer vector) vector with block sizes for the
#' restricted permutation. A block size of 3 indicates that a row can only be permuted
#' within a block of 3 adjacent rows. Default: c(2, 3, 4).
#' @param seed (optional, integer) initial random seed to use for replicability. Default: 1
#' @param repetitions (optional, integer) number of null psi values to generate. Default: 100
#' @return Psi distance
#' @export
null_psi_full_cpp <- function(a, b, method, diagonal = FALSE, weighted = FALSE, trim_blocks = FALSE, block_size = as.integer( c(2, 3, 4)), seed = 1L, repetitions = 100L) {
    .Call(`_distantia_null_psi_full_cpp`, a, b, method, diagonal, weighted, trim_blocks, block_size, seed, repetitions)
}

