#' Resamples Time Series List to a New Time
#'
#' @description
#'
#' Given time series list and a time vector, this function uses Generalized Additive Models (GAM) to resample the time series to a new time. This operation is useful to align time series with different frequencies, or to transform irregular time series into regular.
#'
#' The new time vector must be of the same class as the time of the zoo object (either  numeric, Date, or POSIXct). This new time vector can be either created from scratch, or can be extracted from another zoo object with [zoo::index()].
#'
#' Each time series is modelled as a function of the original time of the zoo object with [mgcv::gam()], and then predicted to the new time.
#'
#' Please use this operation with care, as there are limits to the amount of resampling that can be done without distorting the data. The safest option is to keep the distance between new time points within the same magnitude of the distance between the old time points.
#'
#' This function supports progress bars generated by the `progressr` package. See examples.
#'
#' This function also accepts a parallelization setup via [future::plan()], but it might only be worth it for very long time series.
#'
#'
#' @param tsl (required, list) Time series list. Default: NULL
#' @param time (required, zoo object, or vector of the classes numeric, Date, or POSIXct) New time of the resampled zoo object. Must be of the same class of the time in `x`. If one of them is "numeric" and the other is not, an error is returned. If a zoo object is provided, its time is used as a template to resample `x`. If NULL, irregular time series are predicted into a regular version of their own time, and regular time series are returned as is. Default: NULL
#' @param method (optional, string) Name of the method to resample the time series. One of "spline" (see [utils_optimize_spline()]), "gam" (see [utils_optimize_gam()])  or "loess" (see [utils_optimize_loess()]). Default: "spline".
#' @param max_complexity (required, logical). If TRUE, RMSE optimization is ignored, and the result of a model of maximum complexity is returned. Default: FALSE
#'
#' @return time series list
#' @export
#' @autoglobal
#' @examples
#' #simulate time series list
#' x <- tsl_simulate(
#'   cols = 2,
#'   rows = 50
#' )
#'
#' #plot zoo object
#' tsl_plot(x)
#'
#' #check time
#' tsl_time(x)
#'
#' #new time to first day of each month
#' new_time <- seq.Date(
#'   from = as.Date("2010-01-01"),
#'   to = as.Date("2020-01-01"),
#'   by = "1 month"
#' )
#'
#' #resampling
#' x_new <- tsl_resample(
#'   tsl = x,
#'   time = new_time
#' )
#'
#' #check new time
#' tsl_time(x_new)
#'
#' #plot resampled zoo object
#' tsl_plot(x_new)
tsl_resample <- function(
    tsl = NULL,
    time = NULL,
    method = "spline",
    max_complexity = FALSE
    ){

  tsl <- tsl_is_valid(tsl = tsl)

  #subset time
  old_time <- tsl_time(tsl = tsl)
  old_time_begin <- max(old_time$begin)
  old_time_end <- min(old_time$end)
  old_time_length <- min(old_time$length)

  #if time is null, create a regular one
  if(is.null(time)){

    time <- seq(
      from = old_time_begin,
      to = old_time_end,
      length.out = old_time_length
    )

  } else {

    #time is a zoo object
    if(zoo::is.zoo(time)){
      time <- zoo::index(time)
    }

    if(utils_is_time(x = time) == FALSE){
      time <- utils_as_time(x = time)
    }

    time <- time[time >= old_time_begin & time <= old_time_end]

  }

  #resample
  tsl <- lapply(
    X = tsl,
    FUN = function(x){

      x <- zoo_resample(
        x = x,
        time = time,
        method = method,
        max_complexity = max_complexity
      )

    }
  )

  tsl <- tsl_names_set(
    tsl = tsl
  )

  tsl


}
